/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AceitarConviteRouteImport } from './routes/aceitar-convite'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/_painel'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedSelecionarEmpresaRouteImport } from './routes/_authenticated/selecionar-empresa'
import { Route as StatusSlugRouteImport } from './routes/status.$slug'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedPainelConfiguracoesRouteImport } from './routes/_authenticated/_painel/configuracoes'
import { Route as AuthenticatedPainelDashboardRouteImport } from './routes/_authenticated/_painel/dashboard'
import { Route as AuthenticatedPainelPdvRouteImport } from './routes/_authenticated/_painel/pdv'
import { Route as AuthenticatedPainelAdminGlobalConvitesRouteImport } from './routes/_authenticated/_painel/admin-global/convites'
import { Route as AuthenticatedPainelAdminGlobalEmpresasRouteImport } from './routes/_authenticated/_painel/admin-global/empresas'
import { Route as AuthenticatedPainelAdminGlobalLogsRouteImport } from './routes/_authenticated/_painel/admin-global/logs'
import { Route as AuthenticatedPainelAdminGlobalMetricasRouteImport } from './routes/_authenticated/_painel/admin-global/metricas'
import { Route as AuthenticatedPainelAdminGlobalUsuariosRouteImport } from './routes/_authenticated/_painel/admin-global/usuarios'
import { Route as AuthenticatedPainelInfraAccessMapRouteImport } from './routes/_authenticated/_painel/infra/access-map'
import { Route as AuthenticatedPainelInfraEquipmentsRouteImport } from './routes/_authenticated/_painel/infra/equipments'
import { Route as AuthenticatedPainelInfraPhoneLinesRouteImport } from './routes/_authenticated/_painel/infra/phone-lines'
import { Route as AuthenticatedPainelInfraPhoneStockRouteImport } from './routes/_authenticated/_painel/infra/phone-stock'
import { Route as AuthenticatedPainelInfraServicesAssetsRouteImport } from './routes/_authenticated/_painel/infra/services-assets'
import { Route as ApiPublicAgentHeartbeatRouteImport } from './routes/api/public/agent/heartbeat'
import { Route as ApiPublicCronRunChecksRouteImport } from './routes/api/public/cron/run-checks'
import { Route as ApiPublicHeartbeatTokenRouteImport } from './routes/api/public/heartbeat/$token'
import { Route as AuthenticatedPainelInfraMonitoringIndexRouteImport } from './routes/_authenticated/_painel/infra/monitoring/index'
import { Route as AuthenticatedPainelInfraMonitoringIdRouteImport } from './routes/_authenticated/_painel/infra/monitoring/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AceitarConviteRoute = AceitarConviteRouteImport.update({
  id: '/aceitar-convite',
  path: '/aceitar-convite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/_painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSelecionarEmpresaRoute =
  AuthenticatedSelecionarEmpresaRouteImport.update({
    id: '/selecionar-empresa',
    path: '/selecionar-empresa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const StatusSlugRoute = StatusSlugRouteImport.update({
  id: '/status/$slug',
  path: '/status/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelConfiguracoesRoute =
  AuthenticatedPainelConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelDashboardRoute =
  AuthenticatedPainelDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelPdvRoute = AuthenticatedPainelPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AuthenticatedPainelRoute,
} as any)
const AuthenticatedPainelAdminGlobalConvitesRoute =
  AuthenticatedPainelAdminGlobalConvitesRouteImport.update({
    id: '/admin-global/convites',
    path: '/admin-global/convites',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelAdminGlobalEmpresasRoute =
  AuthenticatedPainelAdminGlobalEmpresasRouteImport.update({
    id: '/admin-global/empresas',
    path: '/admin-global/empresas',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelAdminGlobalLogsRoute =
  AuthenticatedPainelAdminGlobalLogsRouteImport.update({
    id: '/admin-global/logs',
    path: '/admin-global/logs',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelAdminGlobalMetricasRoute =
  AuthenticatedPainelAdminGlobalMetricasRouteImport.update({
    id: '/admin-global/metricas',
    path: '/admin-global/metricas',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelAdminGlobalUsuariosRoute =
  AuthenticatedPainelAdminGlobalUsuariosRouteImport.update({
    id: '/admin-global/usuarios',
    path: '/admin-global/usuarios',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelInfraAccessMapRoute =
  AuthenticatedPainelInfraAccessMapRouteImport.update({
    id: '/infra/access-map',
    path: '/infra/access-map',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelInfraEquipmentsRoute =
  AuthenticatedPainelInfraEquipmentsRouteImport.update({
    id: '/infra/equipments',
    path: '/infra/equipments',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelInfraPhoneLinesRoute =
  AuthenticatedPainelInfraPhoneLinesRouteImport.update({
    id: '/infra/phone-lines',
    path: '/infra/phone-lines',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelInfraPhoneStockRoute =
  AuthenticatedPainelInfraPhoneStockRouteImport.update({
    id: '/infra/phone-stock',
    path: '/infra/phone-stock',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelInfraServicesAssetsRoute =
  AuthenticatedPainelInfraServicesAssetsRouteImport.update({
    id: '/infra/services-assets',
    path: '/infra/services-assets',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const ApiPublicAgentHeartbeatRoute = ApiPublicAgentHeartbeatRouteImport.update({
  id: '/api/public/agent/heartbeat',
  path: '/api/public/agent/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRunChecksRoute = ApiPublicCronRunChecksRouteImport.update({
  id: '/api/public/cron/run-checks',
  path: '/api/public/cron/run-checks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHeartbeatTokenRoute = ApiPublicHeartbeatTokenRouteImport.update({
  id: '/api/public/heartbeat/$token',
  path: '/api/public/heartbeat/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelInfraMonitoringIndexRoute =
  AuthenticatedPainelInfraMonitoringIndexRouteImport.update({
    id: '/infra/monitoring/',
    path: '/infra/monitoring/',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelInfraMonitoringIdRoute =
  AuthenticatedPainelInfraMonitoringIdRouteImport.update({
    id: '/infra/monitoring/$id',
    path: '/infra/monitoring/$id',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/selecionar-empresa': typeof AuthenticatedSelecionarEmpresaRoute
  '/status/$slug': typeof StatusSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
  '/dashboard': typeof AuthenticatedPainelDashboardRoute
  '/pdv': typeof AuthenticatedPainelPdvRoute
  '/admin-global/convites': typeof AuthenticatedPainelAdminGlobalConvitesRoute
  '/admin-global/empresas': typeof AuthenticatedPainelAdminGlobalEmpresasRoute
  '/admin-global/logs': typeof AuthenticatedPainelAdminGlobalLogsRoute
  '/admin-global/metricas': typeof AuthenticatedPainelAdminGlobalMetricasRoute
  '/admin-global/usuarios': typeof AuthenticatedPainelAdminGlobalUsuariosRoute
  '/infra/access-map': typeof AuthenticatedPainelInfraAccessMapRoute
  '/infra/equipments': typeof AuthenticatedPainelInfraEquipmentsRoute
  '/infra/phone-lines': typeof AuthenticatedPainelInfraPhoneLinesRoute
  '/infra/phone-stock': typeof AuthenticatedPainelInfraPhoneStockRoute
  '/infra/services-assets': typeof AuthenticatedPainelInfraServicesAssetsRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/cron/run-checks': typeof ApiPublicCronRunChecksRoute
  '/api/public/heartbeat/$token': typeof ApiPublicHeartbeatTokenRoute
  '/infra/monitoring/$id': typeof AuthenticatedPainelInfraMonitoringIdRoute
  '/infra/monitoring/': typeof AuthenticatedPainelInfraMonitoringIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/selecionar-empresa': typeof AuthenticatedSelecionarEmpresaRoute
  '/status/$slug': typeof StatusSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
  '/dashboard': typeof AuthenticatedPainelDashboardRoute
  '/pdv': typeof AuthenticatedPainelPdvRoute
  '/admin-global/convites': typeof AuthenticatedPainelAdminGlobalConvitesRoute
  '/admin-global/empresas': typeof AuthenticatedPainelAdminGlobalEmpresasRoute
  '/admin-global/logs': typeof AuthenticatedPainelAdminGlobalLogsRoute
  '/admin-global/metricas': typeof AuthenticatedPainelAdminGlobalMetricasRoute
  '/admin-global/usuarios': typeof AuthenticatedPainelAdminGlobalUsuariosRoute
  '/infra/access-map': typeof AuthenticatedPainelInfraAccessMapRoute
  '/infra/equipments': typeof AuthenticatedPainelInfraEquipmentsRoute
  '/infra/phone-lines': typeof AuthenticatedPainelInfraPhoneLinesRoute
  '/infra/phone-stock': typeof AuthenticatedPainelInfraPhoneStockRoute
  '/infra/services-assets': typeof AuthenticatedPainelInfraServicesAssetsRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/cron/run-checks': typeof ApiPublicCronRunChecksRoute
  '/api/public/heartbeat/$token': typeof ApiPublicHeartbeatTokenRoute
  '/infra/monitoring/$id': typeof AuthenticatedPainelInfraMonitoringIdRoute
  '/infra/monitoring': typeof AuthenticatedPainelInfraMonitoringIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/aceitar-convite': typeof AceitarConviteRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/_painel': typeof AuthenticatedPainelRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/selecionar-empresa': typeof AuthenticatedSelecionarEmpresaRoute
  '/status/$slug': typeof StatusSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_authenticated/_painel/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
  '/_authenticated/_painel/dashboard': typeof AuthenticatedPainelDashboardRoute
  '/_authenticated/_painel/pdv': typeof AuthenticatedPainelPdvRoute
  '/_authenticated/_painel/admin-global/convites': typeof AuthenticatedPainelAdminGlobalConvitesRoute
  '/_authenticated/_painel/admin-global/empresas': typeof AuthenticatedPainelAdminGlobalEmpresasRoute
  '/_authenticated/_painel/admin-global/logs': typeof AuthenticatedPainelAdminGlobalLogsRoute
  '/_authenticated/_painel/admin-global/metricas': typeof AuthenticatedPainelAdminGlobalMetricasRoute
  '/_authenticated/_painel/admin-global/usuarios': typeof AuthenticatedPainelAdminGlobalUsuariosRoute
  '/_authenticated/_painel/infra/access-map': typeof AuthenticatedPainelInfraAccessMapRoute
  '/_authenticated/_painel/infra/equipments': typeof AuthenticatedPainelInfraEquipmentsRoute
  '/_authenticated/_painel/infra/phone-lines': typeof AuthenticatedPainelInfraPhoneLinesRoute
  '/_authenticated/_painel/infra/phone-stock': typeof AuthenticatedPainelInfraPhoneStockRoute
  '/_authenticated/_painel/infra/services-assets': typeof AuthenticatedPainelInfraServicesAssetsRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/cron/run-checks': typeof ApiPublicCronRunChecksRoute
  '/api/public/heartbeat/$token': typeof ApiPublicHeartbeatTokenRoute
  '/_authenticated/_painel/infra/monitoring/$id': typeof AuthenticatedPainelInfraMonitoringIdRoute
  '/_authenticated/_painel/infra/monitoring/': typeof AuthenticatedPainelInfraMonitoringIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aceitar-convite'
    | '/auth'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/onboarding'
    | '/selecionar-empresa'
    | '/status/$slug'
    | '/.lovable/oauth/consent'
    | '/configuracoes'
    | '/dashboard'
    | '/pdv'
    | '/admin-global/convites'
    | '/admin-global/empresas'
    | '/admin-global/logs'
    | '/admin-global/metricas'
    | '/admin-global/usuarios'
    | '/infra/access-map'
    | '/infra/equipments'
    | '/infra/phone-lines'
    | '/infra/phone-stock'
    | '/infra/services-assets'
    | '/api/public/agent/heartbeat'
    | '/api/public/cron/run-checks'
    | '/api/public/heartbeat/$token'
    | '/infra/monitoring/$id'
    | '/infra/monitoring/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aceitar-convite'
    | '/auth'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/onboarding'
    | '/selecionar-empresa'
    | '/status/$slug'
    | '/.lovable/oauth/consent'
    | '/configuracoes'
    | '/dashboard'
    | '/pdv'
    | '/admin-global/convites'
    | '/admin-global/empresas'
    | '/admin-global/logs'
    | '/admin-global/metricas'
    | '/admin-global/usuarios'
    | '/infra/access-map'
    | '/infra/equipments'
    | '/infra/phone-lines'
    | '/infra/phone-stock'
    | '/infra/services-assets'
    | '/api/public/agent/heartbeat'
    | '/api/public/cron/run-checks'
    | '/api/public/heartbeat/$token'
    | '/infra/monitoring/$id'
    | '/infra/monitoring'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aceitar-convite'
    | '/auth'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/_painel'
    | '/_authenticated/onboarding'
    | '/_authenticated/selecionar-empresa'
    | '/status/$slug'
    | '/.lovable/oauth/consent'
    | '/_authenticated/_painel/configuracoes'
    | '/_authenticated/_painel/dashboard'
    | '/_authenticated/_painel/pdv'
    | '/_authenticated/_painel/admin-global/convites'
    | '/_authenticated/_painel/admin-global/empresas'
    | '/_authenticated/_painel/admin-global/logs'
    | '/_authenticated/_painel/admin-global/metricas'
    | '/_authenticated/_painel/admin-global/usuarios'
    | '/_authenticated/_painel/infra/access-map'
    | '/_authenticated/_painel/infra/equipments'
    | '/_authenticated/_painel/infra/phone-lines'
    | '/_authenticated/_painel/infra/phone-stock'
    | '/_authenticated/_painel/infra/services-assets'
    | '/api/public/agent/heartbeat'
    | '/api/public/cron/run-checks'
    | '/api/public/heartbeat/$token'
    | '/_authenticated/_painel/infra/monitoring/$id'
    | '/_authenticated/_painel/infra/monitoring/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AceitarConviteRoute: typeof AceitarConviteRoute
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  StatusSlugRoute: typeof StatusSlugRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicAgentHeartbeatRoute: typeof ApiPublicAgentHeartbeatRoute
  ApiPublicCronRunChecksRoute: typeof ApiPublicCronRunChecksRoute
  ApiPublicHeartbeatTokenRoute: typeof ApiPublicHeartbeatTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aceitar-convite': {
      id: '/aceitar-convite'
      path: '/aceitar-convite'
      fullPath: '/aceitar-convite'
      preLoaderRoute: typeof AceitarConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_painel': {
      id: '/_authenticated/_painel'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/selecionar-empresa': {
      id: '/_authenticated/selecionar-empresa'
      path: '/selecionar-empresa'
      fullPath: '/selecionar-empresa'
      preLoaderRoute: typeof AuthenticatedSelecionarEmpresaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/status/$slug': {
      id: '/status/$slug'
      path: '/status/$slug'
      fullPath: '/status/$slug'
      preLoaderRoute: typeof StatusSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_painel/configuracoes': {
      id: '/_authenticated/_painel/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedPainelConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/_painel/dashboard': {
      id: '/_authenticated/_painel/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedPainelDashboardRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/_painel/pdv': {
      id: '/_authenticated/_painel/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof AuthenticatedPainelPdvRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/_painel/admin-global/convites': {
      id: '/_authenticated/_painel/admin-global/convites'
      path: '/admin-global/convites'
      fullPath: '/admin-global/convites'
      preLoaderRoute: typeof AuthenticatedPainelAdminGlobalConvitesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/_painel/admin-global/empresas': {
      id: '/_authenticated/_painel/admin-global/empresas'
      path: '/admin-global/empresas'
      fullPath: '/admin-global/empresas'
      preLoaderRoute: typeof AuthenticatedPainelAdminGlobalEmpresasRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/_painel/admin-global/logs': {
      id: '/_authenticated/_painel/admin-global/logs'
      path: '/admin-global/logs'
      fullPath: '/admin-global/logs'
      preLoaderRoute: typeof AuthenticatedPainelAdminGlobalLogsRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/_painel/admin-global/metricas': {
      id: '/_authenticated/_painel/admin-global/metricas'
      path: '/admin-global/metricas'
      fullPath: '/admin-global/metricas'
      preLoaderRoute: typeof AuthenticatedPainelAdminGlobalMetricasRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/_painel/admin-global/usuarios': {
      id: '/_authenticated/_painel/admin-global/usuarios'
      path: '/admin-global/usuarios'
      fullPath: '/admin-global/usuarios'
      preLoaderRoute: typeof AuthenticatedPainelAdminGlobalUsuariosRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/_painel/infra/access-map': {
      id: '/_authenticated/_painel/infra/access-map'
      path: '/infra/access-map'
      fullPath: '/infra/access-map'
      preLoaderRoute: typeof AuthenticatedPainelInfraAccessMapRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/_painel/infra/equipments': {
      id: '/_authenticated/_painel/infra/equipments'
      path: '/infra/equipments'
      fullPath: '/infra/equipments'
      preLoaderRoute: typeof AuthenticatedPainelInfraEquipmentsRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/_painel/infra/phone-lines': {
      id: '/_authenticated/_painel/infra/phone-lines'
      path: '/infra/phone-lines'
      fullPath: '/infra/phone-lines'
      preLoaderRoute: typeof AuthenticatedPainelInfraPhoneLinesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/_painel/infra/phone-stock': {
      id: '/_authenticated/_painel/infra/phone-stock'
      path: '/infra/phone-stock'
      fullPath: '/infra/phone-stock'
      preLoaderRoute: typeof AuthenticatedPainelInfraPhoneStockRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/_painel/infra/services-assets': {
      id: '/_authenticated/_painel/infra/services-assets'
      path: '/infra/services-assets'
      fullPath: '/infra/services-assets'
      preLoaderRoute: typeof AuthenticatedPainelInfraServicesAssetsRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/api/public/agent/heartbeat': {
      id: '/api/public/agent/heartbeat'
      path: '/api/public/agent/heartbeat'
      fullPath: '/api/public/agent/heartbeat'
      preLoaderRoute: typeof ApiPublicAgentHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/run-checks': {
      id: '/api/public/cron/run-checks'
      path: '/api/public/cron/run-checks'
      fullPath: '/api/public/cron/run-checks'
      preLoaderRoute: typeof ApiPublicCronRunChecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/heartbeat/$token': {
      id: '/api/public/heartbeat/$token'
      path: '/api/public/heartbeat/$token'
      fullPath: '/api/public/heartbeat/$token'
      preLoaderRoute: typeof ApiPublicHeartbeatTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_painel/infra/monitoring/': {
      id: '/_authenticated/_painel/infra/monitoring/'
      path: '/infra/monitoring'
      fullPath: '/infra/monitoring/'
      preLoaderRoute: typeof AuthenticatedPainelInfraMonitoringIndexRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/_painel/infra/monitoring/$id': {
      id: '/_authenticated/_painel/infra/monitoring/$id'
      path: '/infra/monitoring/$id'
      fullPath: '/infra/monitoring/$id'
      preLoaderRoute: typeof AuthenticatedPainelInfraMonitoringIdRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
  }
}

interface AuthenticatedPainelRouteChildren {
  AuthenticatedPainelConfiguracoesRoute: typeof AuthenticatedPainelConfiguracoesRoute
  AuthenticatedPainelDashboardRoute: typeof AuthenticatedPainelDashboardRoute
  AuthenticatedPainelPdvRoute: typeof AuthenticatedPainelPdvRoute
  AuthenticatedPainelAdminGlobalConvitesRoute: typeof AuthenticatedPainelAdminGlobalConvitesRoute
  AuthenticatedPainelAdminGlobalEmpresasRoute: typeof AuthenticatedPainelAdminGlobalEmpresasRoute
  AuthenticatedPainelAdminGlobalLogsRoute: typeof AuthenticatedPainelAdminGlobalLogsRoute
  AuthenticatedPainelAdminGlobalMetricasRoute: typeof AuthenticatedPainelAdminGlobalMetricasRoute
  AuthenticatedPainelAdminGlobalUsuariosRoute: typeof AuthenticatedPainelAdminGlobalUsuariosRoute
  AuthenticatedPainelInfraAccessMapRoute: typeof AuthenticatedPainelInfraAccessMapRoute
  AuthenticatedPainelInfraEquipmentsRoute: typeof AuthenticatedPainelInfraEquipmentsRoute
  AuthenticatedPainelInfraPhoneLinesRoute: typeof AuthenticatedPainelInfraPhoneLinesRoute
  AuthenticatedPainelInfraPhoneStockRoute: typeof AuthenticatedPainelInfraPhoneStockRoute
  AuthenticatedPainelInfraServicesAssetsRoute: typeof AuthenticatedPainelInfraServicesAssetsRoute
  AuthenticatedPainelInfraMonitoringIdRoute: typeof AuthenticatedPainelInfraMonitoringIdRoute
  AuthenticatedPainelInfraMonitoringIndexRoute: typeof AuthenticatedPainelInfraMonitoringIndexRoute
}

const AuthenticatedPainelRouteChildren: AuthenticatedPainelRouteChildren = {
  AuthenticatedPainelConfiguracoesRoute: AuthenticatedPainelConfiguracoesRoute,
  AuthenticatedPainelDashboardRoute: AuthenticatedPainelDashboardRoute,
  AuthenticatedPainelPdvRoute: AuthenticatedPainelPdvRoute,
  AuthenticatedPainelAdminGlobalConvitesRoute:
    AuthenticatedPainelAdminGlobalConvitesRoute,
  AuthenticatedPainelAdminGlobalEmpresasRoute:
    AuthenticatedPainelAdminGlobalEmpresasRoute,
  AuthenticatedPainelAdminGlobalLogsRoute:
    AuthenticatedPainelAdminGlobalLogsRoute,
  AuthenticatedPainelAdminGlobalMetricasRoute:
    AuthenticatedPainelAdminGlobalMetricasRoute,
  AuthenticatedPainelAdminGlobalUsuariosRoute:
    AuthenticatedPainelAdminGlobalUsuariosRoute,
  AuthenticatedPainelInfraAccessMapRoute:
    AuthenticatedPainelInfraAccessMapRoute,
  AuthenticatedPainelInfraEquipmentsRoute:
    AuthenticatedPainelInfraEquipmentsRoute,
  AuthenticatedPainelInfraPhoneLinesRoute:
    AuthenticatedPainelInfraPhoneLinesRoute,
  AuthenticatedPainelInfraPhoneStockRoute:
    AuthenticatedPainelInfraPhoneStockRoute,
  AuthenticatedPainelInfraServicesAssetsRoute:
    AuthenticatedPainelInfraServicesAssetsRoute,
  AuthenticatedPainelInfraMonitoringIdRoute:
    AuthenticatedPainelInfraMonitoringIdRoute,
  AuthenticatedPainelInfraMonitoringIndexRoute:
    AuthenticatedPainelInfraMonitoringIndexRoute,
}

const AuthenticatedPainelRouteWithChildren =
  AuthenticatedPainelRoute._addFileChildren(AuthenticatedPainelRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSelecionarEmpresaRoute: typeof AuthenticatedSelecionarEmpresaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPainelRoute: AuthenticatedPainelRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSelecionarEmpresaRoute: AuthenticatedSelecionarEmpresaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AceitarConviteRoute: AceitarConviteRoute,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  StatusSlugRoute: StatusSlugRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicAgentHeartbeatRoute: ApiPublicAgentHeartbeatRoute,
  ApiPublicCronRunChecksRoute: ApiPublicCronRunChecksRoute,
  ApiPublicHeartbeatTokenRoute: ApiPublicHeartbeatTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
